// List<String> jenenge = [
//   "Anjing Laut",
//   "Anjing",
//   "Ayam Kalkun",
//   "Babi",
//   "Buaya",
//   "Beruang",
//   "Burung Gereja",
//   "Burung Alap-Alap",
//   "Burung Gagak",
//   "Burung Belibis",
//   "Burung Elang",
//   "Bebek",
//   "Cheetah",
//   "Burung Hantu",
//   "Burung Kenari",
//   "Gajah",
//   "Penguin",
//   "Gorilla",
//   "Jaguar",
//   "Harimau",
//   "Katak",
//   "Keledai",
//   "Kuda Nil",
//   "Koala",
//   "Lumba-Lumba",
//   "Kuda",
//   "Serigala",
//   "Paus Beluga",
//   "Paus Orca",
//   "Nyamuk",
//   "Singa Gunung",
//   "Simpanse",
//   "Ruak-Ruak",
//   "Burung Mandar",
//   "Siamang",
// ];
// List<String> gambare = [
//   "anjing_laut.png",
//   "anjing.png",
//   "ayam_kalkun.png",
//   "babi.png",
//   "buaya.png",
//   "beruang.png",
//   "burung_gereja.png",
//   "burung_alap_alap.png",
//   "burung_gagak.png",
//   "burung_belibis.png",
//   "burung_elang.png",
//   "burung_bebek.png",
//   "cheetah.png",
//   "burung_hantu.png",
//   "burung_kenari.png",
//   "gajah.png",
//   "burung_penguin.png",
//   "gorilla.png",
//   "jaguar.png",
//   "harimau.png",
//   "katak.png",
//   "keledai.png",
//   "kuda_nil.png",
//   "koala.png",
//   "lumba_lumba.png",
//   "kuda.png",
//   "serigala.png",
//   "paus_beluga.png",
//   "paus_orca.png",
//   "nyamuk.png",
//   "singa_gunung.png",
//   "simpanse.png",
//   "burung_ruak.png",
//   "burung_mandar.png",
//   "siamang.png",
// ];
// List<String> suarane = [
//   "anjing_laut.mp3",
//   "anjing.mp3",
//   "ayam_kalkun.mp3",
//   "babi.mp3",
//   "buaya.mp3",
//   "beruang.mp3",
//   "burung_gereja.mp3",
//   "burung_alap_alap.mp3",
//   "burung_gagak.mp3",
//   "burung_belibis.mp3",
//   "burung_elang.mp3",
//   "burung_bebek.mp3",
//   "cheetah.mp3",
//   "burung_hantu.mp3",
//   "burung_kenari.mp3",
//   "gajah.mp3",
//   "burung_penguin.mp3",
//   "gorilla.mp3",
//   "jaguar.mp3",
//   "harimau.mp3",
//   "katak.mp3",
//   "keledai.mp3",
//   "kuda_nil.mp3",
//   "koala.mp3",
//   "lumba_lumba.mp3",
//   "kuda.mp3",
//   "serigala.mp3",
//   "paus_beluga.mp3",
//   "paus_orca.mp3",
//   "nyamuk.mp3",
//   "singa_gunung.mp3",
//   "simpanse.mp3",
//   "burung_ruak.mp3",
//   "burung_mandar.mp3",
//   "siamang.mp3",
// ];
